language: php

php:
  - 7.3

before_script:
  - travis_retry composer update
  # disable xdebug if not coverage
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - ./vendor/bin/phpunit